import type { VerificationStatusV1 } from "@stackreplay/schema";
import { BUNDLED_CATALOG, BUNDLED_CATALOG_VERSION } from "./bundled-catalog.js";
import { type CatalogV1, catalogV1Schema } from "./catalog.js";
import { createModelIdentityIndex, type ModelIdentityIndex } from "./resolve.js";
import { selectPlanVersionAt } from "./versions.js";

/**
 * Browser-safe catalog access.
 *
 * The bundled snapshot is the same validated catalog the CLI loads from YAML,
 * embedded as a generated module so it works in a browser, in a Web Worker and
 * in tests with no filesystem, no network request and no YAML parser. Catalog
 * hosting and freshness policy remain a later-milestone question: this is the
 * bundled snapshot the specification describes, not a remote fetch.
 *
 * The snapshot is generated by `scripts/build-bundled.mjs` and guarded against
 * drift by `bundled.test.ts`.
 */

export { BUNDLED_CATALOG_VERSION };

let cached: CatalogV1 | undefined;

/** Returns the bundled catalog, validated once per process. */
export function loadBundledCatalog(): CatalogV1 {
  if (cached !== undefined) return cached;
  const parsed = catalogV1Schema.safeParse(BUNDLED_CATALOG);
  if (!parsed.success) {
    throw new Error(
      `the bundled catalog snapshot is invalid: ${parsed.error.issues[0]?.message ?? "unknown issue"}`,
    );
  }
  cached = parsed.data;
  return cached;
}

let cachedIdentity: ModelIdentityIndex | undefined;

/**
 * The bundled catalog's model identity index (M4A): the same resolution rules the
 * adapters and the engine use, so the browser summary can explain a mapping
 * exactly the way a replay applies it.
 */
export function bundledModelIdentity(): ModelIdentityIndex {
  if (cachedIdentity !== undefined) return cachedIdentity;
  cachedIdentity = createModelIdentityIndex(loadBundledCatalog());
  return cachedIdentity;
}

export interface BundledPlanSummary {
  id: string;
  name: string;
  providerId: string;
  versionId: string;
  effectiveFrom: string;
  price: { amount: string; currency: string; interval: string };
  limitCount: number;
  modelCount: number;
  verificationStatus: string;
}

/**
 * Plans with the version effective at a rules instant, for pickers.
 *
 * Selection goes through the shared rule rather than `array.at(-1)`: relying on
 * the order versions happen to sit in meant a picker could offer a different
 * version than the engine would replay against (benchmark finding F002).
 */
export function bundledPlansAt(rulesAsOf: string): BundledPlanSummary[] {
  const catalog = loadBundledCatalog();
  const summaries: BundledPlanSummary[] = [];
  for (const plan of Object.values(catalog.plans)) {
    const version = selectPlanVersionAt(plan.versions, rulesAsOf);
    if (version === undefined) continue;
    summaries.push({
      id: plan.id,
      name: plan.name,
      providerId: plan.providerId,
      versionId: `${plan.id}@${version.effectiveFrom}`,
      effectiveFrom: version.effectiveFrom,
      price: {
        amount: version.price.amount,
        currency: version.price.currency,
        interval: version.price.interval,
      },
      limitCount: version.limits.length,
      modelCount: version.modelRules.length,
      verificationStatus: version.verificationStatus,
    });
  }
  return summaries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

/** Target facts a share snapshot needs, resolved from the bundled catalog. */
export interface BundledPlanFacts {
  planId: string;
  planVersionId: string;
  planName: string;
  providerId: string;
  providerName: string;
  price: { currency: "USD"; amount: string; interval: "month" | "year" };
  verificationStatus: VerificationStatusV1;
  lastVerifiedAt: string;
  sources: readonly { url: string; title: string }[];
}

/**
 * Full plan-version facts for a resolved target reference, so a surface that
 * already holds a replay result can describe the plan it replayed against
 * without re-deriving anything.
 */
export function bundledPlanFacts(versionId: string): BundledPlanFacts | undefined {
  const catalog = loadBundledCatalog();
  const version = catalog.planVersions[versionId];
  if (version === undefined) return undefined;
  const plan = catalog.plans[version.planId];
  const provider = plan === undefined ? undefined : catalog.providers[plan.providerId];
  return {
    planId: version.planId,
    planVersionId: version.versionId,
    planName: version.planName,
    providerId: version.providerId,
    providerName: provider?.name ?? version.providerId,
    price: {
      currency: version.price.currency,
      amount: version.price.amount,
      interval: version.price.interval,
    },
    verificationStatus: version.verificationStatus,
    lastVerifiedAt: version.lastVerifiedAt,
    sources: version.sources.map((source) => ({ url: source.url, title: source.title })),
  };
}

/**
 * Models a plan version excludes from its included usage but lets subscribers
 * run with usage credits, so a replay can name that paid route instead of
 * reporting the model as simply unavailable.
 */
export function bundledUsageCreditModels(versionId: string): readonly string[] {
  const version = loadBundledCatalog().planVersions[versionId];
  return (version?.modelRules ?? [])
    .filter((rule) => rule.excluded === true && rule.access === "usage_credits")
    .map((rule) => rule.model);
}

/** Provider facts a Direct API surface needs, resolved from the bundled catalog. */
export interface BundledProviderFacts {
  id: string;
  name: string;
  verificationStatus: VerificationStatusV1;
  lastVerifiedAt: string;
  sources: readonly { url: string; title: string }[];
}

export function bundledProviderFacts(providerId: string): BundledProviderFacts | undefined {
  const provider = loadBundledCatalog().providers[providerId];
  if (provider === undefined) return undefined;
  return {
    id: provider.id,
    name: provider.name,
    verificationStatus: provider.verificationStatus,
    lastVerifiedAt: provider.lastVerifiedAt,
    sources: provider.sources.map((source) => ({ url: source.url, title: source.title })),
  };
}

/**
 * One provider a Direct API replay could be run against (M4C), with the counts a
 * picker has to show to be honest about what the replay can then do.
 *
 * A provider qualifies when the catalog records at least one model it offers.
 * `pricedModelCount` is the subset of those models with an API list-price record,
 * so a picker can say up front how much of the catalog's demand could actually be
 * priced rather than letting a replay report it afterwards.
 */
export interface BundledApiProviderSummary {
  id: string;
  name: string;
  /** Models the catalog records this provider as offering. */
  modelCount: number;
  /**
   * Of those, the models with an api_list_price record in force at the instant
   * the summary was taken for. A picker that promised a price the replay then
   * reports as not yet in force would contradict the result it leads to, so the
   * count follows the same effective ranges the engine selects from.
   */
  pricedModelCount: number;
  /** The instant the counts were taken for, when one was given. */
  effectiveAt?: string | undefined;
  verificationStatus: VerificationStatusV1;
}

/**
 * Whether a pricing record's effective range covers an instant. The bounds are
 * inclusive and ISO dates compare lexicographically, which is the same reading
 * `selectPlanVersionAt` applies when the replay picks the record in force.
 */
function coversInstant(
  instant: string,
  record: {
    effectiveFrom: string;
    effectiveTo?: string | undefined;
    effectiveFromInstant?: string | undefined;
  },
): boolean {
  return (
    record.effectiveFrom <= instant &&
    (record.effectiveFromInstant === undefined ||
      Date.parse(instant) >= Date.parse(record.effectiveFromInstant)) &&
    (record.effectiveTo === undefined || instant <= record.effectiveTo)
  );
}

export function bundledApiProviders(rulesAsOf?: string): BundledApiProviderSummary[] {
  const catalog = loadBundledCatalog();
  const priced = new Set(
    Object.values(catalog.pricing)
      .filter(
        (pricing) =>
          pricing.basis === "api_list_price" &&
          (rulesAsOf === undefined || coversInstant(rulesAsOf, pricing)),
      )
      .map((pricing) => pricing.modelId),
  );
  const offered = new Map<string, { modelCount: number; pricedModelCount: number }>();
  for (const model of Object.values(catalog.models)) {
    const isPriced = priced.has(model.id);
    for (const providerId of model.providerIds ?? []) {
      const entry = offered.get(providerId) ?? { modelCount: 0, pricedModelCount: 0 };
      entry.modelCount += 1;
      if (isPriced) entry.pricedModelCount += 1;
      offered.set(providerId, entry);
    }
  }
  const summaries: BundledApiProviderSummary[] = [];
  for (const [providerId, counts] of offered.entries()) {
    const provider = catalog.providers[providerId];
    summaries.push({
      id: providerId,
      name: provider?.name ?? providerId,
      modelCount: counts.modelCount,
      pricedModelCount: counts.pricedModelCount,
      ...(rulesAsOf !== undefined ? { effectiveAt: rulesAsOf } : {}),
      verificationStatus: provider?.verificationStatus ?? "unknown",
    });
  }
  return summaries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

/**
 * Provider routes with an authoritative Direct API offer in the public picker.
 * Copilot and Cursor token rates belong to target billing. The explicitly
 * labeled example providers remain available for bundled demo workloads.
 */
export const PUBLIC_API_PROVIDER_IDS: ReadonlySet<string> = new Set([
  "anthropic",
  "deepseek",
  "example-cloud",
  "example-open",
  "google",
  "openai",
  "x-ai",
  "z-ai",
]);

export function bundledPublicApiProviders(rulesAsOf?: string): BundledApiProviderSummary[] {
  return bundledApiProviders(rulesAsOf).filter((provider) =>
    PUBLIC_API_PROVIDER_IDS.has(provider.id),
  );
}

/**
 * The public Direct API providers the catalog records as offering a model.
 * This is an offering fact, not a claim about who built the model: the catalog
 * does not record authorship, and nothing here infers it.
 */
export function directApiProviderIdsFor(catalog: CatalogV1, modelId: string): string[] {
  return (catalog.models[modelId]?.providerIds ?? []).filter((id) =>
    PUBLIC_API_PROVIDER_IDS.has(id),
  );
}

/** One model a target can run, for a scenario picker. */
export interface BundledTargetModel {
  id: string;
  name: string;
  /**
   * For a subscription: the plan's rule names the model and does not exclude
   * it. For a Direct API provider: the provider is recorded as offering it.
   */
  available: boolean;
  /** Direct API only: an api_list_price record is in force at the rules date. */
  priced?: boolean;
}

/**
 * The models a subscription plan's version in force at `rulesAsOf` names, with
 * excluded models marked unavailable. The same rule the engine applies: a model
 * the plan's rules do not name is not served.
 */
export function bundledPlanModelsAt(
  planId: string,
  rulesAsOf: string,
): { versionId: string; models: BundledTargetModel[] } | undefined {
  const catalog = loadBundledCatalog();
  const plan = catalog.plans[planId];
  if (plan === undefined) return undefined;
  const version = selectPlanVersionAt(plan.versions, rulesAsOf);
  if (version === undefined) return undefined;
  const models = version.modelRules.map((rule) => ({
    id: rule.model,
    name: catalog.models[rule.model]?.name ?? rule.model,
    available: rule.excluded !== true,
  }));
  return {
    versionId: `${plan.id}@${version.effectiveFrom}`,
    models: models.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0)),
  };
}

/**
 * The models a Direct API provider is recorded as offering, with whether a list
 * price is in force at `rulesAsOf`: the same offering and pricing facts the API
 * replay reads.
 */
export function bundledApiProviderModels(
  providerId: string,
  rulesAsOf: string,
): BundledTargetModel[] {
  const catalog = loadBundledCatalog();
  const priced = new Set(
    Object.values(catalog.pricing)
      .filter((pricing) => pricing.basis === "api_list_price" && coversInstant(rulesAsOf, pricing))
      .map((pricing) => pricing.modelId),
  );
  return Object.values(catalog.models)
    .filter((model) => model.providerIds?.includes(providerId) === true)
    .map((model) => ({
      id: model.id,
      name: model.name,
      available: true,
      priced: priced.has(model.id),
    }))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}
