import type { VerificationStatusV1 } from "@stackreplay/schema";
import { BUNDLED_CATALOG, BUNDLED_CATALOG_VERSION } from "./bundled-catalog.js";
import { type CatalogV1, catalogV1Schema } from "./catalog.js";
import { createModelIdentityIndex, type ModelIdentityIndex } from "./resolve.js";

/**
 * Browser-safe catalog access.
 *
 * The bundled snapshot is the same validated catalog the CLI loads from YAML,
 * embedded as a generated module so it works in a browser, in a Web Worker and
 * in tests with no filesystem, no network request and no YAML parser. Catalog
 * hosting and freshness policy remain a later-milestone question: this is the
 * bundled snapshot the specification describes, not a remote fetch.
 *
 * The snapshot is generated by `scripts/build-bundled.mjs` and guarded against
 * drift by `bundled.test.ts`.
 */

export { BUNDLED_CATALOG_VERSION };

let cached: CatalogV1 | undefined;

/** Returns the bundled catalog, validated once per process. */
export function loadBundledCatalog(): CatalogV1 {
  if (cached !== undefined) return cached;
  const parsed = catalogV1Schema.safeParse(BUNDLED_CATALOG);
  if (!parsed.success) {
    throw new Error(
      `the bundled catalog snapshot is invalid: ${parsed.error.issues[0]?.message ?? "unknown issue"}`,
    );
  }
  cached = parsed.data;
  return cached;
}

let cachedIdentity: ModelIdentityIndex | undefined;

/**
 * The bundled catalog's model identity index (M4A): the same resolution rules the
 * adapters and the engine use, so the browser summary can explain a mapping
 * exactly the way a replay applies it.
 */
export function bundledModelIdentity(): ModelIdentityIndex {
  if (cachedIdentity !== undefined) return cachedIdentity;
  cachedIdentity = createModelIdentityIndex(loadBundledCatalog());
  return cachedIdentity;
}

export interface BundledPlanSummary {
  id: string;
  name: string;
  providerId: string;
  versionId: string;
  effectiveFrom: string;
  price: { amount: string; currency: string; interval: string };
  limitCount: number;
  modelCount: number;
  verificationStatus: string;
}

/** Plans with the version effective at a rules instant, for pickers. */
export function bundledPlansAt(rulesAsOf: string): BundledPlanSummary[] {
  const catalog = loadBundledCatalog();
  const summaries: BundledPlanSummary[] = [];
  for (const plan of Object.values(catalog.plans)) {
    const version = plan.versions
      .filter(
        (entry) =>
          entry.effectiveFrom <= rulesAsOf &&
          (entry.effectiveTo === undefined || entry.effectiveTo >= rulesAsOf),
      )
      .at(-1);
    if (version === undefined) continue;
    summaries.push({
      id: plan.id,
      name: plan.name,
      providerId: plan.providerId,
      versionId: `${plan.id}@${version.effectiveFrom}`,
      effectiveFrom: version.effectiveFrom,
      price: {
        amount: version.price.amount,
        currency: version.price.currency,
        interval: version.price.interval,
      },
      limitCount: version.limits.length,
      modelCount: version.modelRules.length,
      verificationStatus: version.verificationStatus,
    });
  }
  return summaries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

/** Target facts a share snapshot needs, resolved from the bundled catalog. */
export interface BundledPlanFacts {
  planId: string;
  planVersionId: string;
  planName: string;
  providerId: string;
  providerName: string;
  price: { currency: "USD"; amount: string; interval: "month" | "year" };
  verificationStatus: VerificationStatusV1;
  lastVerifiedAt: string;
  sources: readonly { url: string; title: string }[];
}

/**
 * Full plan-version facts for a resolved target reference, so a surface that
 * already holds a replay result can describe the plan it replayed against
 * without re-deriving anything.
 */
export function bundledPlanFacts(versionId: string): BundledPlanFacts | undefined {
  const catalog = loadBundledCatalog();
  const version = catalog.planVersions[versionId];
  if (version === undefined) return undefined;
  const plan = catalog.plans[version.planId];
  const provider = plan === undefined ? undefined : catalog.providers[plan.providerId];
  return {
    planId: version.planId,
    planVersionId: version.versionId,
    planName: version.planName,
    providerId: version.providerId,
    providerName: provider?.name ?? version.providerId,
    price: {
      currency: version.price.currency,
      amount: version.price.amount,
      interval: version.price.interval,
    },
    verificationStatus: version.verificationStatus,
    lastVerifiedAt: version.lastVerifiedAt,
    sources: version.sources.map((source) => ({ url: source.url, title: source.title })),
  };
}
