/** GENERATED from the bundled catalog; labels and version only. */
export const BUNDLED_CATALOG_VERSION =
  "sha256:6be2d332c9448e271ad64435beca23dc5b4b09880fd0940f0561729e917556c6";
export const MODEL_NAMES: Record<string, string> = {
  "amazon-nova-2-lite": "Amazon Nova 2 Lite",
  "claude-fable-5-1": "Claude Fable 5.1",
  "claude-fable-5": "Claude Fable 5",
  "claude-fable": "Fable",
  "claude-haiku-4-5": "Claude Haiku 4.5",
  "claude-haiku": "Haiku",
  "claude-opus-4-5": "Claude Opus 4.5",
  "claude-opus-4-6": "Claude Opus 4.6",
  "claude-opus-4-7": "Claude Opus 4.7",
  "claude-opus-4-8-fast-mode": "Claude Opus 4.8 (fast mode) (preview)",
  "claude-opus-4-8": "Claude Opus 4.8",
  "claude-opus-5-5": "Claude Opus 5.5",
  "claude-opus-5": "Claude Opus 5",
  "claude-opus": "Opus",
  "claude-sonnet-4-5": "Claude Sonnet 4.5",
  "claude-sonnet-4-6": "Claude Sonnet 4.6",
  "claude-sonnet-4": "Claude Sonnet 4",
  "claude-sonnet-5-5": "Claude Sonnet 5.5",
  "claude-sonnet-5": "Claude Sonnet 5",
  "claude-sonnet": "Sonnet",
  "cohere-command-a-plus": "Command A+",
  "cohere-north-mini-code": "North Mini Code",
  "composer-2-5": "Composer 2.5",
  "deepseek-v3-2": "DeepSeek 3.2",
  "deepseek-v4-1-flash": "DeepSeek-V4.1-Flash",
  "deepseek-v4-flash-vision-exp": "DeepSeek-V4-Flash-Vision-Exp (legacy name, model retired)",
  "deepseek-v4-flash": "DeepSeek-V4-Flash (legacy name, model retired)",
  "deepseek-v4-pro": "DeepSeek-V4-Pro-0813",
  "example-large": "Example Large",
  "example-medium": "Example Medium",
  "example-small": "Example Small",
  "gemini-3-1-flash-lite": "Gemini 3.1 Flash Lite",
  "gemini-3-1-pro": "Gemini 3.1 Pro",
  "gemini-3-5-flash-lite": "Gemini 3.5 Flash Lite",
  "gemini-3-5-flash": "Gemini 3.5 Flash",
  "gemini-3-6-flash": "Gemini 3.6 Flash",
  "gemini-3-7-flash": "Gemini 3.7 Flash",
  "gemini-3-8-flash": "Gemini 3.8 Flash",
  "gemini-3-flash-lite": "Gemini 3 Flash-Lite",
  "gemini-3-flash": "Gemini 3 Flash",
  "gemini-3-pro": "Gemini 3 Pro",
  "gemini-4-argon": "Gemini 4 Argon",
  "gemma-4": "Gemma 4",
  "glm-5-1": "GLM 5.1",
  "glm-5-2": "GLM 5.2",
  "glm-5-3-flash": "GLM 5.3 Flash",
  "glm-5-3-flashx": "GLM 5.3 FlashX",
  "glm-5-3": "GLM 5.3",
  "glm-5": "GLM 5",
  "gpt-5-3-codex": "GPT-5.3-Codex",
  "gpt-5-4-mini": "GPT-5.4 mini",
  "gpt-5-4-nano": "GPT-5.4 nano",
  "gpt-5-4": "GPT-5.4",
  "gpt-5-5": "GPT-5.5",
  "gpt-5-6-luna": "GPT-5.6 Luna",
  "gpt-5-6-sol-pro": "GPT-5.6 Sol Pro",
  "gpt-5-6-sol": "GPT-5.6 Sol",
  "gpt-5-6-terra": "GPT-5.6 Terra",
  "gpt-5-mini": "GPT-5 mini",
  "gpt-5-thinking-mini": "GPT-5 Thinking Mini",
  "gpt-6-1-sol": "GPT-6.1 Sol",
  "gpt-6-astra": "GPT-6 Astra",
  "gpt-6-luna": "GPT-6 Luna",
  "gpt-6-sol": "GPT-6 Sol",
  "gpt-oss-120b": "GPT-OSS 120B",
  "gpt-oss-20b": "GPT-OSS 20B",
  "grok-4-5": "Grok 4.5",
  "grok-4-6": "Grok 4.6",
  "grok-4-7": "Grok 4.7",
  hy3: "Tencent Hy3",
  "inkling-small": "Inkling Small",
  inkling: "Inkling",
  "kimi-k2-5": "Kimi K2.5",
  "kimi-k2-6": "Kimi K2.6",
  "kimi-k2-7-code": "Kimi K2.7 Code",
  "kimi-k3": "Kimi K3",
  "laguna-s-2-1": "Laguna S 2.1",
  "llama-4-maverick": "Llama 4 Maverick",
  "llama-4-scout": "Llama 4 Scout",
  "longcat-2-0": "LongCat 2.0",
  "mai-code-1-1-flash": "MAI-Code-1.1-Flash",
  "mimo-v2-5-pro": "MiMo V2.5 Pro",
  "mimo-v2-5": "MiMo V2.5",
  "mimo-v2-6-flash": "MiMo V2.6 Flash",
  "mimo-v2-6-pro": "MiMo V2.6 Pro",
  "minimax-m2-1": "MiniMax M2.1",
  "minimax-m2-5": "MiniMax M2.5",
  "minimax-m2-7": "MiniMax M2.7",
  "minimax-m3": "MiniMax M3",
  "mistral-large-3": "Mistral Large 3",
  "muse-spark-1-1": "Muse Spark 1.1",
  "muse-spark-1-2": "Muse Spark 1.2",
  "muse-spark-1-3": "Muse Spark 1.3",
  "nano-banana-pro": "Nano Banana Pro",
  "nemotron-3-nano": "Nemotron 3 Nano",
  "nemotron-3-super": "Nemotron 3 Super",
  "nemotron-3-ultra": "Nemotron 3 Ultra",
  "qwen-3-6-plus": "Qwen 3.6 Plus",
  "qwen-3-7-flash": "Qwen 3.7 Flash",
  "qwen-3-7-max": "Qwen 3.7 Max",
  "qwen-3-7-plus": "Qwen 3.7 Plus",
  "qwen-3-8-27b": "Qwen 3.8 27B",
  "qwen-3-8-flash": "Qwen 3.8 Flash",
  "qwen-3-8-max-0902": "Qwen 3.8 Max 0902",
  "qwen-3-8-max": "Qwen 3.8 Max",
  "qwen-3-8-omni-flash": "Qwen 3.8 Omni Flash",
  "qwen3-coder-next": "Qwen3 Coder Next",
  "step-3-5-flash": "Step 3.5 Flash",
  "step-3-7-flash": "Step 3.7 Flash",
};
