import type { ProjectedReplayV1 } from "@stackreplay/replay-engine";
import rawArtifact from "@stackreplay/test-fixtures/generated/m4d-demo.json";

/**
 * The engine-backed demonstration artifact, as a surface reads it.
 *
 * The file is generated by `apps/web/scripts/build-demo-artifact.mjs`, which
 * runs the production engine over a deterministic synthetic month, and it is
 * committed. The cast is confined to this one place because the JSON module's
 * inferred type is structural, not nominal: `demo-artifact.test.ts` regenerates
 * the file and fails if it drifts from the engine, so the artifact is guarded by
 * a test rather than by a duplicated type.
 *
 * Importing JSON keeps the demonstration free of network calls and of any
 * runtime file access, which is what the local-first rule requires.
 */

export interface DemoArtifactTarget {
  id: string;
  label: string;
  detail: string;
  kind: "subscription" | "api";
  translated: boolean;
  projection: ProjectedReplayV1;
}

export interface DemoArtifactSource {
  adapterId: string;
  name: string;
  role: string;
}

export interface DemoArtifactScenario {
  id: string;
  title: string;
  description: string;
  eventCount: number;
  range: { from: string; to: string };
  sources: readonly DemoArtifactSource[];
  translationPolicy: {
    id: string;
    version: string;
    name: string;
    provenance: string;
    transform: string;
    rules: readonly { sourceModelId: string; targetModelId: string }[];
  };
}

export interface DemoArtifactUnknownSample {
  eventCount: number;
  unmappedModel: string;
  projection: ProjectedReplayV1;
}

export interface DemoArtifact {
  artifactVersion: number;
  generatedBy: string;
  engineVersion: string;
  methodologyVersion: string;
  catalogVersion: string;
  rulesAsOf: string;
  scenario: DemoArtifactScenario;
  targets: readonly DemoArtifactTarget[];
  unknownSample: DemoArtifactUnknownSample;
}

export function loadDemoArtifact(): DemoArtifact {
  return rawArtifact as unknown as DemoArtifact;
}

/** The default target: the first entry, which the generator emits in a fixed order. */
export function defaultDemoTargetId(artifact: DemoArtifact): string {
  return artifact.targets[0]?.id ?? "";
}

export function findDemoTarget(
  artifact: DemoArtifact,
  targetId: string | undefined,
): DemoArtifactTarget | undefined {
  if (targetId === undefined) return artifact.targets[0];
  return artifact.targets.find((target) => target.id === targetId) ?? artifact.targets[0];
}
