/**
 * The Replay choreography, as a pure timeline.
 *
 * The sequence lives here rather than inside the component so it can be tested
 * without a browser, and so the meaning of each step is written down where the
 * copy that describes it lives. The motion explains computation: each phase
 * names the thing the engine actually did, in the order it did it.
 *
 * A translation step exists only for a translated replay. An exact replay must
 * not show a substitution it never performed, so the sequence itself omits the
 * phase rather than rendering it empty.
 */

export type ReplayPhase =
  | "observed"
  | "identity"
  | "translation"
  | "target"
  | "pressure"
  | "settled";

export interface ReplayStep {
  phase: ReplayPhase;
  /** Milliseconds from the start of the run at which this phase becomes current. */
  at: number;
}

const STEP_MS = {
  observed: 350,
  identity: 400,
  translation: 300,
  target: 400,
  pressure: 500,
} as const;

/** What each phase is saying, in the interface's own words. */
export const PHASE_CAPTIONS: Record<ReplayPhase, string> = {
  observed: "Observed workload · recorded before the replay, not generated by it",
  identity: "Model identity · resolving observed identifiers against the catalog",
  translation: "Scenario translation · substituting a model under an explicit assumption",
  target: "Target execution stack · applying the selected target's rules",
  pressure: "Chronology · advancing the workload through the target's windows",
  settled: "Result settled",
};

export const PHASE_LABELS: Record<ReplayPhase, string> = {
  observed: "Observed",
  identity: "Identity",
  translation: "Translation",
  target: "Target",
  pressure: "Chronology",
  settled: "Result",
};

export function sequenceFor(translated: boolean): readonly ReplayStep[] {
  const phases: ReplayPhase[] = translated
    ? ["observed", "identity", "translation", "target", "pressure", "settled"]
    : ["observed", "identity", "target", "pressure", "settled"];
  let at = 0;
  const steps: ReplayStep[] = [];
  for (const phase of phases) {
    steps.push({ phase, at });
    at += phase === "settled" ? 0 : STEP_MS[phase];
  }
  return steps;
}

/** Total run length: ~1.65s exact, ~1.95s with an explicit substitution. */
export function totalDurationMs(translated: boolean): number {
  const steps = sequenceFor(translated);
  return steps.at(-1)?.at ?? 0;
}

export function phaseAt(elapsedMs: number, translated: boolean): ReplayPhase {
  const steps = sequenceFor(translated);
  let current: ReplayPhase = steps[0]?.phase ?? "settled";
  for (const step of steps) {
    if (elapsedMs >= step.at) current = step.phase;
  }
  return current;
}

export function phaseIndex(phase: ReplayPhase, translated: boolean): number {
  return sequenceFor(translated).findIndex((step) => step.phase === phase);
}

/** True when `phase` is at or past `other` in this run's own sequence. */
export function phaseAtLeast(phase: ReplayPhase, other: ReplayPhase, translated: boolean): boolean {
  return phaseIndex(phase, translated) >= phaseIndex(other, translated);
}

/**
 * The animations a phase drives, named by the thing that reacts. Layers read
 * this instead of comparing raw phases, so "what moves when" has one definition.
 */
export interface PhaseEffects {
  workloadActive: boolean;
  identityActive: boolean;
  translationActive: boolean;
  targetActive: boolean;
  chronologyActive: boolean;
  settled: boolean;
}

export function effectsAt(phase: ReplayPhase, translated: boolean): PhaseEffects {
  return {
    workloadActive: phaseAtLeast(phase, "observed", translated),
    identityActive: phaseAtLeast(phase, "identity", translated),
    translationActive: translated && phaseAtLeast(phase, "translation", translated),
    targetActive: phaseAtLeast(phase, "target", translated),
    chronologyActive: phaseAtLeast(phase, "pressure", translated),
    settled: phase === "settled",
  };
}
